// front-end/gui-api-react-redux/src/App.js
import React from 'react'
import Menu from './Menu'
import Form from './Form'
import Info from './Info'
import Table from './Table'
import Pagehand from './Pagehand'

export const App = () => {
    return (
        <div className="row">
            <div className="column" id="wc1">
                <Menu />
            </div>
            <div className="column" id="wc2">
                <Form />
                <Info />
            </div>
            <div className="column" id="wc3">
                <Table />
                <Pagehand />
            </div>
        </div>
    )
}

export default App

// front-end/gui-api-vue/src/App.vue
<template>
  <div class="row">
    <div class="column" id="wc1">
      <Menu />
    </div>
    <div class="column" id="wc2">
      <Form />
      <Info />
    </div>
    <div class="column" id="wc3">
      <Table />
      <Pagehand />
    </div>
  </div>
</template>

<script>
import Menu from "@/Menu"
import Form from "@/Form"
import Table from "@/Table"
import Pagehand from "@/Pagehand"
import Info from "@/Info"
export default {
  name: "App",
  components: {Info, Menu, Form, Table, Pagehand }
}
</script>
