// front-end/gui-api-react/src/Menu.js
import React from 'react'
import serv_data from './services/serv_data'

/**
 * Rendering the Menu commands (the 1-st column)
 */

const Menu = (props) => {                       // Menu list generation
    const { customerId, onClick } = props
    const rows = serv_data.map((row, index) => {      // Creating an array with menu items <li>
        const menuClass = ((index < 2) || (customerId)) ? 'act' : 'disact'
        return (
            <li key={index}>
                <a className="nav-link active" className={menuClass}
                   onClick={() => onClick(index)}>{serv_data[index].title}</a>
            </li>
        )
    })

    return (
        <ul className="nav justify-content-end">
            {rows}
        </ul>
    )
}

export default Menu

// front-end/gui-api-vue/src/Menu.vue
<template>
    <ul class="nav justify-content-end">
      <div v-for="(row, index) in menu">
        <li key={index}>
          <a class="nav-link" :class="menuClass(index)"
             @click="$store.commit('setIndex', index)" >{{row.title}}</a>
        </li>
      </div>
    </ul>
</template>

<script>
import serv_data from './services/serv_data'
import { mapGetters } from 'vuex'
export default {
  name: "Menu",
  data() {
    return {
      menu: serv_data
    }
  },
  computed: {
    ...mapGetters({
      customerId : 'getCustomer'
    })
  },
  methods: {
    menuClass(index) {
       return (
           ((index < 2) || (this.customerId)) ? "act" : "disact"
       )
    }
  }
}
</script>

<style>
  .act {
    font-weight: bold;
    pointer-events: auto;
  }
  .disact {
    font-weight: normal;
    pointer-events: none;
  }
</style>
