// front-end/gui-api-vue/src/Pagehand.vue
<template>
  <div class="row">

    <!-- Go to next/previous page - Buttons: "Previous"/"Next" -->
    <div class="col-sm-6">
      <ul class="pager" >
        <li><a @click="$store.commit('previousPage')">&#9650;&nbsp;&nbsp; Previous</a></li>
        <li><a @click="$store.commit('nextPage')">&#9660;&nbsp;&nbsp; Next</a></li>
      </ul>
    </div>

    <!-- Page size setting - Radio buttons -->
    <div class="col-sm-6" >
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" id="rad1"
               @change="$store.commit('setPage', PAGE1)" :checked="page === PAGE1" />
        <label class="form-check-label" for="rad1">&nbsp; Page=5</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" id="rad2"
               @change="$store.commit('setPage', PAGE2)" :checked="page === PAGE2" />
        <label class="form-check-label" for="rad2">&nbsp; Page=10</label>
      </div>
    </div>

  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import { PAGE1, PAGE2 } from './services/serv_data'
export default {
  name: "Pagehand",
  data() {
    return {
      PAGE1: PAGE1,
      PAGE2: PAGE2,
    }
  },
  computed: {
    ...mapGetters({
      page: 'getPage'
    })
  }
}
</script>

// front-end/gui-api-react/src/Pagehand.js
import React from "react"
import { PAGE1, PAGE2 } from './services/serv_data'

/**
 * Page output handling:
 * - Page changing
 * - Page size setting
 */

const Pagination = (props) => {             // Go to next/previous page - Buttons: "Previous"/"Next"
    const { pagePrevious, pageNext } = props
    return (
        <div className="column nest" className="col-sm-6">
            <ul className="pager">
                <li><a onClick={pagePrevious}>&#9650;&nbsp;&nbsp; Previous</a></li>
                <li><a onClick={pageNext}>&#9660;&nbsp;&nbsp; Next</a></li>
            </ul>
        </div>
    )
}

const PageSetting = (props) => {            // Page size setting - Radio buttons
    const { setPage, page } = props
    return (
        <div className="column nest" className="col-sm-6" style={{padding: "10px 0 0 40px"}}>
            <div className="form-check">
                <input className="form-check-input" type="radio" id="rad1"
                      onChange={() => setPage(PAGE1)} checked={page === PAGE1} />
                <label className="form-check-label" htmlFor="rad1">&nbsp; Page=5</label>
            </div>
            <div className="form-check">
                <input className="form-check-input" type="radio" id="rad2"
                       onChange={() => setPage(PAGE2)} checked={page === PAGE2} />
                <label className="form-check-label" htmlFor="rad2">&nbsp; Page=10</label>
            </div>
        </div>
    )
}

const Pagehand = (props) => {               // Page handling
    const { pageNext, pagePrevious, setPage, page } = props
    return (
        <div className="row">
            <Pagination pageNext={pageNext} pagePrevious={pagePrevious}/>
            <PageSetting setPage={setPage} page={page} />
        </div>
    )
}

export default Pagehand
