// front-end/gui-api-vue/src/Table.vue
<template>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">TransactionId</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody id="db_tab" v-for="(row, ind) in rows">
        <tr key={ind}>
          <td>{{row.transactionId}}</td>
          <td>{{row.amount}}</td>
          <td>{{row.date}}</td>
        </tr>
    </tbody>
  </table>
</template>

<script>
import { mapGetters } from 'vuex'
import store from "@/store"
export default {
  name: "Table",
  computed: {
    ...mapGetters({
      db: 'getTrans',
      offset: 'getOffset',
      page: 'getPage'
    }),
    rows() {
      const {db, offset, page} = this
      return db.filter((el, index) => ((index >= offset) && (index < offset + page)))
    }
  },
  watch: {
    db() {
      store.commit('resetOffset')}
  }
}
</script>

// front-end/gui-api-react/src/Table.js
import React from "react"

/**
 * Outputting the database table:
 * - Displaying the table header
 * - Displaying the table body
 */

const TableHeader = () => {         // Table header displaying
    return (
        <thead>
        <tr>
            <th scope="col">TransactionId</th>
            <th scope="col">Amount</th>
            <th scope="col">Date</th>
        </tr>
        </thead>
    )
}

const TableBody = (props) => {        // Generation of DB-table
    const {db, offset, page} = props
    let rows = db.map((row, index) => {
        return (
            <tr key={index}>
                <td>{row.transactionId}</td>
                <td>{row.amount}</td>
                <td>{row.date}</td>
            </tr>
        )
    })

    // Selection from the table of the output page
    rows = rows.filter((el, index) => ((index >= offset) && (index < offset + page)))

    return (
        <tbody id="db_tab">
            {rows}
        </tbody> )
}

const Table = (props) => {                  // Database table displaying
    const { db, offset, page } = props
    return (
        <table className="table">
            <TableHeader />
            <TableBody db={db} offset={offset} page={page} />
        </table>
    )
}

export default Table
