// front-end/gui-api-react-redux/src/components/TransTable.js
import React from 'react'
import Box from '@mui/material/Box'
import { Paper } from "@mui/material"
import { Table } from "@mui/material"
import { TableBody } from "@mui/material"
import { TableCell } from "@mui/material"
import { TableContainer } from "@mui/material"
import { TableHead } from "@mui/material"
import { TableRow } from "@mui/material"
import { Toolbar } from "@mui/material"
import { Button } from '@mui/material'
import { Stack } from '@mui/material'
import NavigateBeforeIcon from "@mui/icons-material/NavigateBefore"
import NavigateNextIcon from "@mui/icons-material/NavigateNext"
import {connect} from "react-redux"
import { nextPage, previousPage } from "../store/actions/transAction"
import store from "../index";

export const TransTable = (props) => {
    const { previousDisabled, nextDisabled, tabAr } = props

    return (
        <Box component="main" sx={{ flexGrow: 1, p: 2 }}>
            <Toolbar />
            <TableContainer component={Paper}>
                <Table size="small" aria-label="a dense table">
                    <TableHead>
                        <TableRow>
                            <TableCell><b>TransactionId</b></TableCell>
                            <TableCell><b>Amount</b></TableCell>
                            <TableCell><b>Date</b></TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        { tabAr.map((item, index) => (
                            <TableRow key={index}>
                                <TableCell>{item.transactionId}</TableCell>
                                <TableCell>{item.amount}</TableCell>
                                <TableCell>{item.date}</TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>

            <Stack direction="row" spacing={2} ml={2} mt={2}>
                <Button variant="outlined" startIcon={<NavigateBeforeIcon />}
                        disabled={previousDisabled} 
                        onClick={() => store.dispatch(previousPage())}>
                    Previous
                </Button>
                <Button variant="outlined" startIcon={<NavigateNextIcon />}
                        disabled={nextDisabled} 
                        onClick={() => store.dispatch(nextPage())} >
                    Next
                </Button>
            </Stack>
        </Box>
    )
}
const mapStateToProps = state => ({
    previousDisabled: state.transRed.previousDisabled,
    nextDisabled: state.transRed.nextDisabled,
    tabAr: state.transRed.tabAr
})

export default connect(mapStateToProps)(TransTable)

// front-end/gui-api-vue-vuex/src/components/TransTable.vue
<template>
  <div>
    <v-table density="compact">
      <colgroup>
        <col style="width: 20%;">
        <col style="width: 20%;">
        <col style="width: 60%;">
      </colgroup>

      <thead>
        <tr>
          <th class="text-left"><b>TransactionId</b></th>
          <th class="text-left"><b>Amount</b></th>
          <th class="text-left"><b>Date</b></th>
        </tr>
      </thead>

      <tbody>
        <tr v-for="(item, index) in tabAr" :key="index">
          <td>{{ item.transactionId }}</td>
          <td>{{ item.amount }}</td>
          <td>{{ item.date }}</td>
        </tr>
      </tbody>
    </v-table>

    <v-divider class="my-2"/>

    <v-row class="mt-4 ml-4" align="center">
      <v-btn
        variant="outlined"
        color="primary"
        :disabled="previousDisabled"
        @click="() => store.commit('previousPage')"
        prepend-icon="mdi-chevron-left"
      >
        Previous
      </v-btn>

      <v-btn
        variant="outlined"
        color="primary"
        :disabled="nextDisabled"
        @click="() => store.commit('nextPage')"
        prepend-icon="mdi-chevron-right"
        class="ml-2"
      >
        Next
      </v-btn>
    </v-row>
  </div>    
</template>

<script setup>
import store from '@/store'
import { computed } from 'vue'

const tabAr = computed(() => store.state.transMod.tabAr)
const previousDisabled = computed(() => store.state.transMod.previousDisabled)
const nextDisabled = computed(() => store.state.transMod.nextDisabled)
</script>
