// front-end/gui-api-react-redux/src/components/TransDialog.js
import React from 'react'
import { Dialog } from "@mui/material"
import { DialogTitle } from "@mui/material"
import { IconButton } from "@mui/material"
import CloseIcon from "@mui/icons-material/Close"
import SendIcon from "@mui/icons-material/Send"
import { DialogContent } from "@mui/material"
import { TextField } from "@mui/material"
import { DialogActions } from "@mui/material"
import { Button } from "@mui/material"
import { connect } from "react-redux"
import { fetchTrans } from "../store/actions/transAction"
import store from "../index"
import { closeTrans } from "../store/actions/modalWindAction"

export const TransDialog = (props) => {
    const { open, command } = props

    const transRequest = () => {         // Interacting with Transaction DB
        const payload = {}      // Input values for request (for creating url)
        
        let el = document.getElementById('transactionId')
        payload.transactionId = (el) ? el.value : ''

        el = document.getElementById('amount')
        payload.amount = (el) ? el.value : ''

        el = document.getElementById('date')
        payload.date = (el) ? el.value : ''

        store.dispatch(() => fetchTrans(payload))
        store.dispatch(closeTrans())
    }

        // Data for creating input dialogs 
        const inpData = {
            ['Add Transaction'] : [{ id: 'amount', label: 'Amount', type: 'number' }],
            ['Get Transaction'] : [{ id: 'transactionId', label: 'TransactionId', type: 'number' }],
            ['Get Transaction by Filter'] : [{ id: 'amount', label: 'Amount', type: 'number' },
                                                { id: 'date', label: '', type: 'date' }],
            ['Update Transaction'] : [{ id: 'transactionId', label: 'TransactionId', type: 'number' },
                                        { id: 'amount', label: 'Amount', type: 'number' }],
            ['Delete Transaction'] : [{ id: 'transactionId', label: 'TransactionId', type: 'number' }],
            [''] : []
        }

    return (
        <Dialog open={open} maxWidth="xs" fullWidth={true}
                onClose={() => store.dispatch(closeTrans())}>
            <DialogTitle>
                <IconButton
                    aria-label="close"
                    onClick={() => store.dispatch(closeTrans())}
                    sx={{
                        position: 'absolute',
                        right: 8,
                        top: 8,
                        color: (theme) => theme.palette.grey[700]
                    }}
                >
                    <CloseIcon />
                </IconButton>
            </DialogTitle>
            <DialogContent>
                {inpData[command].map((command, index) => (
                    <TextField key={index}
                        margin="dense"
                        id={command.id}
                        label={command.label}
                        type={command.type}
                        fullWidth
                        variant="standard"
                    />
                ))}
            </DialogContent>
            <DialogActions>
                <Button variant="outlined" startIcon={<SendIcon />} onClick={transRequest}>
                    Submit
                </Button>
            </DialogActions>
        </Dialog>
    )
}

const mapStateToProps = state => ({
    open: state.modalWindRed.transOpen,
    command: state.transRed.command
})

export default connect(mapStateToProps)(TransDialog)

// front-end/gui-api-vue-vuex/src/components/TransDialog.vue
<template>
    <v-dialog
        v-model="store.state.transMod.transOpen"
        width="auto"
    >

        <v-card width="400" class="position-relative">
        <!-- Close icon -->
            <v-btn
                icon="mdi-close"
                class="close-button"
                @click="store.commit('closeTrans')"
                variant="text"
            />

            <v-card-text>
                <v-row v-for="(inp, index) in inpData[store.state.transMod.command]" :key="index">
                    <v-col cols="12">
                        <v-text-field :id="inp.id" :label="inp.label" :type="inp.type"></v-text-field>
                    </v-col>
                </v-row>
            </v-card-text>
            <v-card-actions>
                <v-btn color="primary" variant="outlined" prepend-icon="mdi-send"
                    @click="transRequest">Submit</v-btn>
            </v-card-actions>
        </v-card>
    </v-dialog>
</template>

<script setup>
import store from '@/store'

// Data for creating an input dialog for the selected comand
const inpData = {}
inpData['Add Transaction'] = [{ id: 'amount', label: 'Amount', type: 'number' }]
inpData['Get Transaction'] = [{ id: 'transactionId', label: 'TransactionId', type: 'number' }]
inpData['Get Transaction by Filter'] = [{ id: 'amount', label: 'Amount', type: 'number' },
                                        { id: 'date', label: '', type: 'date' }]
inpData['Update Transaction'] = [{ id: 'transactionId', label: 'TransactionId', type: 'number' },
                                { id: 'amount', label: 'Amount', type: 'number' }]
inpData['Delete Transaction'] = [{ id: 'transactionId', label: 'TransactionId', type: 'number' }]
inpData[''] = []

const transRequest = () => {
        const payload = {}      // Object with input values for request (for creating url)

        switch (store.state.transMod.command) {
            case 'Add Transaction':
                payload.amount = document.getElementById('amount').value
                break

            case 'Get Transaction':
                payload.transactionId = document.getElementById('transactionId').value
                break

            case 'Get Transaction by Filter':
                payload.amount = document.getElementById('amount').value
                payload.date = document.getElementById('date').value
                break

            case 'Update Transaction':
                payload.transactionId = document.getElementById('transactionId').value
                payload.amount = document.getElementById('amount').value
                break

            case 'Delete Transaction':
                payload.transactionId = document.getElementById('transactionId').value
                break

            default:
        }

        store.commit('closeTrans'),
        store.dispatch('fetchTrans', payload)
    }
</script>
<style scoped>
.close-button {
  position: absolute;
  top: 8px;
  right: 8px;
  color: #616161;
  z-index: 1;
}
</style>
