// front-end/gui-api-vue-vuex/src/pages/TransPage.vue
<template>
  <v-app>

    <v-app-bar app>
      <NavBar />
    </v-app-bar>

    <v-navigation-drawer
      v-model="drawer"
      location="left"
      app
      width="240"
      permanent
    >
      <v-list density="compact">
        <v-list-item
          v-for="(command, index) in transactionCommands"
          :key="index"
          density="compact"
          @click="() => {
            store.commit('openTrans');
            store.commit('setCommand', command);
          }"
        >
          {{ command }}
        </v-list-item>
      </v-list>
    </v-navigation-drawer>

    <v-main class="d-flex" app>
      <TransTable />
    </v-main>

    <TransDialog />

  </v-app> 
</template>

<script setup>
import { ref } from 'vue'
import NavBar from "@/components/NavBar.vue"
import TransTable from "@/components/TransTable.vue"
import TransDialog from "@/components/TransDialog.vue"
import store from '../store'
const drawer = ref(true)

const transactionCommands = [
  'Add Transaction',
  'Get Transaction',
  'Get Transaction by Filter',
  'Update Transaction',
  'Delete Transaction'
]
</script>

// front-end/gui-api-react-redux/src/pages/TransPage.js
import React, { useEffect } from "react"
import { useNavigate } from "react-router-dom"
import { useSelector } from "react-redux"
import { Drawer, Toolbar} from "@mui/material"
import Box from '@mui/material/Box'
import List from '@mui/material/List'
import ListItem from '@mui/material/ListItem'
import ListItemButton from '@mui/material/ListItemButton'
import ListItemText from '@mui/material/ListItemText'
import TransDialog from "../components/TransDialog"
import TransTable from "../components/TransTable"
import NavBar from "../components/NavBar"
import store from '../index'
import { setCommand } from "../store/actions/transAction"
import { openTrans } from "../store/actions/modalWindAction"

const drawerWidth = 240

const TransPage = () => {
    let navigate = useNavigate()
    const customerId = useSelector(state => state.custRed.customerId)

    useEffect(() => {
        if ( customerId === null ) {
            navigate('/')              // Go to page <HomePage>
        }
    }, [customerId])

    const menuHandler = (command) => {
        store.dispatch(setCommand(command))
        store.dispatch(openTrans())
    }

    return (
        <Box sx={{ display: 'flex' }}>
            <NavBar />

            <Drawer variant="permanent"
                    sx={{
                        width: drawerWidth,
                        flexShrink: 0,
                        [`& .MuiDrawer-paper`]: { width: drawerWidth, boxSizing: 'border-box' },
                    }}
            >
                <Toolbar />
                <Box sx={{ overflow: 'auto' }}>
                    <List>
                        {[
                            'Add Transaction',
                            'Get Transaction',
                            'Get Transaction by Filter',
                            'Update Transaction',
                            'Delete Transaction'
                        ].map((command) => (
                        <ListItem key={command} disablePadding>
                            <ListItemButton onClick={() => menuHandler(command)}>
                                <ListItemText primary={command} />
                            </ListItemButton>
                        </ListItem>
                        ))}
                    </List>
                </Box>
            </Drawer>

            <TransTable />

            <TransDialog />
        </Box>
    )
}

export default TransPage
